name: Publish Release

on:
  release:
    types: [released]

env:
  ARCHIVE_NAME: compiler-${{ github.event.release.tag_name }}

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v3
      - name: Build release
        run: |
          mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && cd ..
          cmake --build build --config Release
          mkdir install && cmake --install build --prefix install --config Release
          cd install && zip -r ../${{ env.ARCHIVE_NAME }}-linux.zip *
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}-linux.zip
          asset_name: ${{ env.ARCHIVE_NAME }}-linux.zip
          asset_content_type: application/zip

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v3
      - name: Build release
        run: |
          mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && cd ..
          cmake --build build --config Release
          mkdir install && cmake --install build --prefix install --config Release
          cd install && zip -r ../${{ env.ARCHIVE_NAME }}-mac.zip *
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}-mac.zip
          asset_name: ${{ env.ARCHIVE_NAME }}-mac.zip
          asset_content_type: application/zip
