name: Test on LLVM

on:
  - push
  - pull_request

jobs:
  ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v3
      - name: Run script
        run: |
          patch ./scripts/test.sh < ./scripts/llvm.patch
          ./scripts/test.sh

  macos:
    name: macOS Big Sur 11
    runs-on: macos-11
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v3
      - name: Set up environment
        run: brew install coreutils
      - name: Run script
        run: |
          patch ./scripts/test.sh < ./scripts/llvm.patch
          ./scripts/test.sh
